#!/bin/bash -x

virt-install \
   --name=amazonuk \
   --controller type=scsi,model=virtio-scsi \
   --disk path=/var/lib/libvirt/images/amazonuk,size=8,sparse=true,cache=none,bus=scsi \
   --graphics vnc,listen=0.0.0.0,port=5952 \
   --network bridge=kvm0-vlan21 \
   --network bridge=kvm0-vlan52 \
   --vcpus=1 --ram=1024 \
   --cdrom=/var/storage/os/CentOS-7-x86_64-Minimal-1511.iso \
   --os-type=linux \
   --os-variant=rhel7

